### ISSUE TITLE
Error for pregen world MVS 4.1 1.20 [FORGE]

### ISSUE THREAD

**Issue by DonorKrovi** [FinnSetchell/MoogsVanillaStructuresV2#22] opened 2023-10-26 12:50 UTC
[14:47:30] [C2ME worker #3/ERROR] [minecraft/StructureTemplateManager]: Couldn't load structure mvs:nature/mushroom_pond/mushroom_pond_upper
net.minecraft.ReportedException: Loading NBT data
        at net.minecraft.nbt.CompoundTag.m_128413_(CompoundTag.java:480) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:c2me-base.mixins.json:access.INbtCompound from mod c2me_base,pl:mixin:APP:c2me-opts-allocs.mixins.json:MixinNbtCompound from mod c2me_opts_allocs,pl:mixin:A}
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:45) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:classloading}
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:32) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:classloading}
        at net.minecraft.nbt.ListTag$1.m_7300_(ListTag.java:43) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:classloading}
        at net.minecraft.nbt.ListTag$1.m_7300_(ListTag.java:26) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:classloading}
        at net.minecraft.nbt.CompoundTag.m_128413_(CompoundTag.java:474) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:c2me-base.mixins.json:access.INbtCompound from mod c2me_base,pl:mixin:APP:c2me-opts-allocs.mixins.json:MixinNbtCompound from mod c2me_opts_allocs,pl:mixin:A}
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:45) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:classloading}
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:32) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:classloading}
        at net.minecraft.nbt.NbtIo.m_128930_(NbtIo.java:153) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading}
        at net.minecraft.nbt.NbtIo.m_128934_(NbtIo.java:99) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading}
        at net.minecraft.nbt.NbtIo.m_128939_(NbtIo.java:35) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230377_(StructureTemplateManager.java:227) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.StructureTemplateManagerAccessor from mod repurposed_structures,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor from mod mvs,pl:mixin:A}
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230372_(StructureTemplateManager.java:217) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.StructureTemplateManagerAccessor from mod repurposed_structures,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor from mod mvs,pl:mixin:A}
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230427_(StructureTemplateManager.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.StructureTemplateManagerAccessor from mod repurposed_structures,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor from mod mvs,pl:mixin:A}
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230425_(StructureTemplateManager.java:108) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.StructureTemplateManagerAccessor from mod repurposed_structures,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor from mod mvs,pl:mixin:A}
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?] {re:mixin}
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230407_(StructureTemplateManager.java:98) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.StructureTemplateManagerAccessor from mod repurposed_structures,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor from mod mvs,pl:mixin:A}
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230359_(StructureTemplateManager.java:86) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.StructureTemplateManagerAccessor from mod repurposed_structures,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor from mod mvs,pl:mixin:A}
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%2377!/:?] {}
        at net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_227299_(SinglePoolElement.java:81) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.SinglePoolElementAccessor from mod repurposed_structures,pl:mixin:APP:mvs-common.mixins.json:structures.SinglePoolElementAccessor from mod mvs,pl:mixin:A}
        at net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_214015_(SinglePoolElement.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.SinglePoolElementAccessor from mod repurposed_structures,pl:mixin:APP:mvs-common.mixins.json:structures.SinglePoolElementAccessor from mod mvs,pl:mixin:A}
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:58) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.PoolElementStructurePieceAccessor from mod repurposed_structures,pl:mixin:APP:mvs-common.mixins.json:structures.PoolElementStructurePieceAccessor from mod mvs,pl:mixin:APP:c2me-fixes-worldgen-threading-issues.mixins.json:asm.ASMTargets from mod c2me_fixes_worldgen_threading_issues,pl:mixin:A}
        at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.m_192753_(PiecesContainer.java:73) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:classloading}
        at net.minecraft.world.level.levelgen.structure.StructureStart.m_226857_(StructureStart.java:57) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:c2me-fixes-worldgen-threading-issues.mixins.json:threading.MixinStructureStart from mod c2me_fixes_worldgen_threading_issues,pl:mixin:APP:c2me-base.mixins.json:access.IStructureStart from mod c2me_base,pl:mixin:A}
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_188254_(ChunkSerializer.java:454) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer from mod architectury,pl:mixin:APP:fabric-registry-sync-v0.mixins.json:ChunkSerializerMixin from mod fabric_registry_sync_v0,pl:mixin:APP:c2me-threading-chunkio.mixins.json:MixinChunkSerializer from mod c2me_threading_chunkio,pl:mixin:APP:antixray.mixins.json:ChunkSerializerMixin from mod antixray,pl:mixin:A}
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_188230_(ChunkSerializer.java:199) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer from mod architectury,pl:mixin:APP:fabric-registry-sync-v0.mixins.json:ChunkSerializerMixin from mod fabric_registry_sync_v0,pl:mixin:APP:c2me-threading-chunkio.mixins.json:MixinChunkSerializer from mod c2me_threading_chunkio,pl:mixin:APP:antixray.mixins.json:ChunkSerializerMixin from mod antixray,pl:mixin:A}
        at net.minecraft.server.level.ChunkMap.md125d1d$c2me_threading_chunkio$lambda$loadChunk$3$15(ChunkMap.java:5530) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkumulator.mixins.json:ThreadedAnvilChunkStorageMixin from mod chunkumulator,pl:mixin:APP:fabric-networking-api-v1.mixins.json:accessor.ThreadedAnvilChunkStorageAccessor from mod fabric_networking_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:ThreadedAnvilChunkStorageMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:c2me-fixes-worldgen-threading-issues.mixins.json:threading.checks.MixinThreadedAnvilChunkStorage from mod c2me_fixes_worldgen_threading_issues,pl:mixin:APP:c2me-fixes-general-threading-issues.mixins.json:MixinThreadedAnvilChunkStorage from mod c2me_fixes_general_threading_issues,pl:mixin:APP:c2me-base.mixins.json:access.IThreadedAnvilChunkStorage from mod c2me_base,pl:mixin:APP:c2me-base.mixins.json:scheduler.MixinThreadedAnvilChunkStorage from mod c2me_base,pl:mixin:APP:c2me-threading-lighting.mixins.json:MixinThreadedAnvilChunkStorage from mod c2me_threading_lighting,pl:mixin:APP:c2me-threading-chunkio.mixins.json:MixinThreadedAnvilChunkStorage from mod c2me_threading_chunkio,pl:mixin:APP:c2me-opts-scheduling.mixins.json:fix_unload.MixinThreadedAnvilChunkStorage from mod c2me_opts_scheduling,pl:mixin:APP:c2me-opts-scheduling.mixins.json:general_overheads.MixinThreadedAnvilChunkStorage from mod c2me_opts_scheduling,pl:mixin:APP:c2me-opts-scheduling.mixins.json:idle_tasks.autosave.disable_vanilla_mid_tick_autosave.MixinThreadedAnvilChunkStorage from mod c2me_opts_scheduling,pl:mixin:APP:c2me-opts-scheduling.mixins.json:idle_tasks.autosave.enhanced_autosave.MixinThreadedAnvilChunkStorage from mod c2me_opts_scheduling,pl:mixin:APP:c2me-opts-scheduling.mixins.json:task_scheduling.MixinThreadedAnvilChunkStorage from mod c2me_opts_scheduling,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?] {re:mixin}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?] {}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
Caused by: java.io.IOException: Invalid tag id: 19
        at net.minecraft.nbt.TagType$1.m_197591_(TagType.java:58) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:classloading}
        at net.minecraft.nbt.TagType$1.m_7300_(TagType.java:63) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:classloading}
        at net.minecraft.nbt.TagType$1.m_7300_(TagType.java:56) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:classloading}
        at net.minecraft.nbt.CompoundTag.m_128413_(CompoundTag.java:474) ~[server-1.20.1-20230612.114412-srg.jar%23209!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:c2me-base.mixins.json:access.INbtCompound from mod c2me_base,pl:mixin:APP:c2me-opts-allocs.mixins.json:MixinNbtCompound from mod c2me_opts_allocs,pl:mixin:A}
        ... 31 more
[14:47:31] [Worker-Main-15/ERROR] [minecraft/SculkShriekerBlockEntity]: No key selector in MapLike[{event_delay:0,event_distance:0.0f,range:8,source:{pos:[I;-425,-56,-205],type:"minecraft:block"}}]

**Comment by FinnSetchell** [comment] 2023-10-26 17:08
Duplicate of #20

**Closed as completed** 2023-10-26 17:09 UTC
